Update bin/compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,39 +1,86 @@
-# apache
-#mkdir /app
-wget http://apache.cyberuse.com//httpd/httpd-2.2.19.tar.gz
-tar xvzf httpd-2.2.19.tar.gz
-cd httpd-2.2.19
-./configure --prefix=/app/apache --enable-rewrite
-make
-make install
-cd ..
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-# php
-wget http://us2.php.net/get/php-5.3.6.tar.gz/from/us.php.net/mirror 
-mv mirror php.tar.gz
-tar xzvf php.tar.gz
-cd php-5.3.6/
-./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs --with-mysql --with-pdo-mysql --with-pgsql --with-pdo-pgsql --with-iconv --with-gd --with-curl=/usr/lib --with-config-file-path=/app/php --enable-soap=shared --with-openssl
-make
-make install
-cd ..
+# fail fast
+set -e
 
-# php extensions
-mkdir /app/php/ext
-cp /usr/lib/libmysqlclient.so.15 /app/php/ext/
+# config
+APACHE_VERSION="2.2.22"
+APACHE_PATH="apache"
+PHP_VERSION="5.3.10"
+PHP_PATH="php"
 
-# pear
-apt-get install php5-dev php-pear
-pear config-set php_dir /app/php
-pecl install apc
-mkdir /app/php/include/php/ext/apc
-cp /usr/lib/php5/20060613/apc.so /app/php/ext/
-cp /usr/include/php5/ext/apc/apc_serializer.h /app/php/include/php/ext/apc/
+BIN_DIR=$(dirname $0)
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+# include .files when moving things around
+shopt -s dotglob
+
+cd $BUILD_DIR
+
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
+fi
+
+APACHE_URL="https://s3.amazonaws.com/php-lp/apache-$APACHE_VERSION.tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
+
+PHP_URL="https://s3.amazonaws.com/php-lp/php-$PHP_VERSION.tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
+
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
+
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
+
+export set PATH=$PATH:$BUILD_DIR/php/bin
 
 
-# package
-cd /app
-echo '2.2.19' > apache/VERSION
-tar -zcvf apache.tar.gz apache
-echo '5.3.6' > php/VERSION
-tar -zcvf php.tar.gz php
+
+# check if we have Composer dependencies and vendors are not bundled
+if [ -f www/composer.json ] && [ ! -d www/vendor ]; then
+  GIT_DIR_ORIG=$GIT_DIR
+  unset GIT_DIR
+  echo "-----> Installing Composer dependencies"
+  COMPOSER_URL="http://getcomposer.org/composer.phar"
+  curl --silent --max-time 60 --location "$COMPOSER_URL" > www/composer.phar
+  cd www
+  LD_LIBRARY_PATH=$BUILD_DIR/php/ext $BUILD_DIR/php/bin/php composer.phar install --prefer-source -v
+  cd $BUILD_DIR
+  rm www/composer.phar
+  export GIT_DIR=$GIT_DIR_ORGI
+else
+  echo "Please check if you have a composer.json file in the root, and that your vendor directory is not committed"
+fi
+
+cat >>boot.sh <<EOF
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
+done
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+export LD_LIBRARY_PATH=/app/php/ext
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
+
+chmod +x boot.sh
+
+# clean the cache
+rm -rf $CACHE_DIR/*
